[project]
name = "buildtogether"
version = "0.1.0"
dependencies = [
    "mccole",
    "ruff",
]

[tool.mccole]
skips = ["old", "templates"]

[tool.mccole.renames]
"CODE_OF_CONDUCT.md" = "code_of_conduct.md"
"CONTRIBUTING.md" = "contributing.md"
"LICENSE.md" = "license.md"
"README.md" = "index.md"
